
image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: cd warehouse; mvn install -Djdk.gtk.version=2; cd ui; mvn javafx:run
  - init: sdk use java 16.0.1.hs-adpt
    command: cd warehouse; mvn install -DskipUiTests -DskipTests; cd springboot/server; mvn spring-boot:run
  - init: cd webapp; yarn
    command: yarn start

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
  - port: 3000
  - port: 8080

vscode:
  extensions:
    - vscjava.vscode-java-pack
