image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd warehouse
    - mvn compile

test:
  stage: test
  script:
    - cd warehouse
    - mvn test
  only:
    - merge_requests
