stages:
  - Java build
  - Java test
  - Webapp build
  - Webapp lint

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn

Build:
  image: maven:3-openjdk-16
  stage: Java build
  script:
    - cd warehouse
    - mvn compile
  retry: 1

Jacoco:
  image: maven:3-openjdk-16
  stage: Java test
  needs: []
  script:
    - cd warehouse
    - mvn test -Dtest=!WarehouseControllerTest -DfailIfNoTests=false
    - mvn jacoco:report-aggregate
    - cat $CI_BUILDS_DIR/$CI_PROJECT_PATH/warehouse/report/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/warehouse/report/target/site/jacoco-aggregate/*
  retry: 2

Spotbugs:
  image: maven:3-openjdk-16
  stage: Java test
  needs: []
  script:
    - cd warehouse
    - mvn install -DskipTests -DskipUiTests -DfailIfNoTests=false
    - mvn spotbugs:check
  retry: 2

Checkstyle:
  image: maven:3-openjdk-16
  stage: Java test
  needs: []
  script:
    - cd warehouse
    - mvn checkstyle:check
  retry: 2

Yarn Build:
  image: node:16.3.0
  stage: Webapp build
  needs: []
  script:
    - cd webapp
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

Prettier check:
  image: node:16.3.0
  stage: Webapp lint
  needs: []
  script:
    - cd webapp
    - npx prettier --check .
  retry: 1
